lsf: 
    user: "user"
    password: "test123"
mail: 
    sender: "mail@mail.mail"
    reciver: "noten@mail.mail"
    password: "geheim"
    smtpServer: "smtp.mail.server"
    smtpPort: "587"
#Setzte diese Variable auf true um einen Notenspiegel zu hosten
webpage: false
mailgun:
    domain: ""
    api-key: ""
    sender-name: "Notenservice"
    reciver: ""
    subject: "Notenupdate!"
smtpmail-mail: false
mailgun-mail: true
domain: "http://localhost:3412"
#updateIntervall: 60
storage: "/var/noten/store.noten"